- configure.ac
- nbd-server.c
It's done by using Win32's FSCTL_SET_ZERO_DATA ioctl.
---
Despite the name, FSCTL_SET_ZERO_DATA is the right API to punch holes on Windows, even on non-sparse files: I can easily punch a 10 GB hole in milliseconds, which wouldn't be achievable if this ioctl were just writing zeros in a loop.
This ioctl is supported since (I think) Windows 2000, so basically available everywhere.
> Support trim on Cygwin

- configure.ac
People may mix a new kernel with an old glibc.
> Check fallocate function first

- nbd-server.c
- nbdsrv.h
If we expect an export file to appear and know its size, we can
temporarily save writes into diff file. When the file appears
we commit all writes into it and switch writes to export file.
This mode can be useful when live migrating VM between hypervisors:
We start mirroring writes from source HV to destination despite
the destination storage doesn't exist yet. Then we can start
copying the source storage (ZFS, LVM, ...) to destination and
when it appears on destination, cached writes are commited to it.
> implemented waiting for file

- .travis.yml
- nbd-server.c
- tests/run/Makefile.am
- tests/run/nbd-tester-client.c
- tests/run/simple_test
This series of patches restores proper functioning of the inetd mode in `nbd-server`. It also adds inetd mode testing to the test suite. Merging it will resolve #75.
Implementing the latter part required some fairly invasive refactoring of the test client. The testing functions are no longer involved with establishing the transport socket connection; they are handed the socket file descriptor already set up, although they still need to perform NBD protocol negotiation. The name of the protocol-negotiating function was kept as `setup_connection_common`, although it is no longer called from the `setup_*_connection` family of functions.
> inetd mode fix

- configure.ac
Introduce --without-gnutls and --without-libnl configure options so that
users can disable gnutls/libnl even if the packages are available on the
system. The default is unchanged from before this patch. If no
--with(out)-* option has been given on the command line, the macro looks
for presence and uses the packages if found.
> Don't make gnutls and libnl automagic

- nbd-server.c
When nbd-server drops privileges, it was leaving supplementary
groups untouched. As nbd-server was normally dropping from root,
nbd-server kept membership to root supplementary groups.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
For example:
```
$ cat config
[generic]
user = nobody
group = nobody
oldstyle = false
[export1]
exportname = /dev/zero
$ sudo ./nbd-server -d --config-file config.example
$ ps -eo pid,comm,euser,egroup,supgrp | grep nbd
5068 nbd-server      nobody   nogroup  root,socked
```
After the patch:
```
$ ps -eo pid,comm,euser,egroup,supgrp | grep nbd
4958 nbd-server      nobody   nogroup  (null)
```
> server: clean supplementary groups when setuid

- nbd-client.c
When we are operating as a daemon we ignore unset (zero) timeout in
set_timeout() and don't set it in kernel.
However, when operating in the netlink mode netlink_configure() will add
NBD_ATTR_TIMEOUT attribute unconditionally.
This means that in the default case of timeout being unset it was being set
to zero in the kernel which resulted in it triggering almost immediately
upon any I/O request.
Fix this by not appending the timeout attribute in netlink_configure() when
the timeout is unset.
This should fix #71
> Don't set unset (zero) timeout in nbd-client when configuring via netlink

- configure.ac
With dash (0.5.9.1) linked to /bin/sh (actual shell should not matter), I get the following error on configure and a subsequent compliation failure because of lacking LIBS flags.
$ ./configure
(...)
checking for libnl-genl-3.0 >= 3.1... yes  
./configure: 14578: ./configure: CFLAGS+= -I/usr/include/libnl3: not found  
./configure: 14579: ./configure: LIBS+= -lnl-genl-3 -lnl-3: not found  
(...)
The diff below corrects the variable appending and compilation.
> correct shell variable assignment for libnl flags in configure(.ac)

- nbd-server.c
When HUP-signal is sent to nbd-server, append_new_servers()
function is executed and it looks up new "max_threads" value
from configuration.  Unfortunately, when such a value is not
provided by configuration, it uses an uninitialized memory value
for it.  Most often this is a big number such as 32612, and
no serious issues arise.  However, sometimes this might be zero,
depending on memory usage patterns, thus leading to max threads
value of 0 provided to g_thread_pool_set_max_threads(), meaning
that all nbd data sends are stopped.  In this situation all new
clients negotiate with server just fine, but they receive no data.
In this fix the real configuration data is used, or the default
of four threads if configuration does not provide a value.
(The issue can be worked around by setting …
> Use the real genconf.threads, not an uninitialized value

- cliserv.h
- tests/code/Makefile.am
err() is a function available in the C library, so when static linking,
there is a clash at link time because the function is provided both by
nbd and the C library:
http://autobuild.buildroot.org/results/aa8/aa8a1ac35a93e1c8b9fddbc2b5d66ecaa921f31e/build-end.log
Fix that by renaming err() to nbd_err() and providing a small macro
wrapper to avoid touching the many call sites.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/nbd/0001-avoid-name-clashing.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> rename err() function to avoid clashing with err() form C library

- configure.ac
$enable_manpages should be used instead of $enablemanpages
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix --disable-manpages

- nbdsrv.c
- tests/code/clientacl.c
For v6-mapped address authentication, when comparing the client IP address
with the address in the authentication file, we should skip the first
12 identical prefixes and compare the real IP address.
This Fixes: #137
> nbd-server: fix bug in authentication for v6-mapped IPv4 addresses

- man/nbd-server.1.in.sgml
- nbd-server.c
This pull requests addresses #132 by adding the new option -n/--nodaemon to nbd-server. When set, it keeps the main process in the foreground, while still allowing to fork the serving process for a client. Functionally, it should be equivalent to providing NODAEMON to the preprocessor.
The commit also fixes a minor inaccuracy in the usage() function, which wrongly stated that the long option of -M is --max-connections (with trailing 's'). While conceptually unrelated, I've still included it as it's a trivial fix; let me know in case I should take it out.
I should note that I'm completely new to the nbd codebase, thus hoping I didn't miss anything relevant. Did some manual testing though (using live ebuild on Gentoo + patch to build it and then playing around with a few client connections) …
> nbd-server: Add option to not daemonize main process

- Makefile.am
nbdtab_lexer.l includes nbdtab_parser.tab.h, which in turn is dynamically generated during the build from nbdtab_parser.y. Specifying nbdtab_parser.tab.h in BUILT_SOURCES avoids a potential race condition where parallel make can fail if nbdtab_lexer.l is processed before nbdtab_parser.tab.h has been created.
Fixes: #140
> Avoid sporadic race condition due to parallel make

- nbd-server.c
The function given to g_array_set_clear_func() for clearing server arrays gets a pointer to server pointer as a parameter instead of simply pointer to server structure.  This change adds a wrapper function removing one level of indirection. Before this change, when arrays are freed, the serve_dec_ref() would decrement random stuff in memory and rarely call free() to some random memory address, crashing nbd-server.
> Fix server array reference counting.

- crypto-gnutls.c
- crypto-gnutls.h
- nbd-client.c
- nbdclt.h
see https://lists.debian.org/nbd/2023/08/msg00009.html
> add option for gnutls priority string

- nbd-client.c
Currently setting port= in nbdtab is accepted, but doesn't take effect. This change fixes it.
> fix port setting from nbdtab

- nbd-client.c
Commit 915444bc0b8a931d32dfb755542f4bd1d37f1449 introduced a regression whereby an entry in *nbdtab* with no port specification was read as wanting port "0" rather than the default "10809".
I attempted to run the current master branch within a test VM but could not get it to connect to the test server using configuration stored in *nbdtab*. However, using command line options worked happily; `strace` of the process eventually confirmed it was attempting to connect to port 0 rather than the expected port 10809 which pointed to a configuration parsing error.
> Set sensible default for port

- configure.ac
Currently, running `configure --disable-manpages` while `docbook2man` *is* installed results in the error "don't know what to do here" when it should disable building of manpages (I ran into this when attempting a build on Ubuntu jammy, finding the manpages didn't want to build, and thinking "I'll just disable that for the moment", and then finding I couldn't disable it :).
There also appears to be a missing conditional at the start of the line; there's closing un-matched ]) at the end of the line. Still, at this point the check can be done in pure shell, no need for AC macros. I've also removed the confusing `m4_divert_text` call on the check case. Not sure why that was there, but it appears unnecessary.
> Fix the "disabled" case of enable_manpages

- nbd-server.c
Clang 14 on macOS 12.7.4 (and I guess also newer versions) emits these warnings when compiling nbd-server.c:
```
CC       nbd_server-nbd-server.o
nbd-server.c:2885:15: warning: & has lower precedence than !=; != will be evaluated first [-Wparentheses]
if(req->type & NBD_CMD_FLAG_DF != 0) {
^~~~~~~~~~~~~~~~~~~~~~
nbd-server.c:2885:15: note: place parentheses around the '!=' expression to silence this warning
if(req->type & NBD_CMD_FLAG_DF != 0) {
^ ~~~~~~~~~~~~~~~~~~~~
nbd-server.c:2885:15: note: place parentheses around the & expression to evaluate it first
if(req->type & NBD_CMD_FLAG_DF != 0) {
~~~~~~~~~~^~~~~~~~~~~~~~~~~
nbd-server.c:3315:10: warning: result of comparison of constant 18446744073709551614 with expression of type 'uint32_t' (aka 'unsigned int') is always false …
```
> fix clang 14 warnings in nbd-server.c

- cliserv.c
- cliserv.h
- nbd-server.c
- nbdsrv.h
Reason: for consistency with existing output functions in the C std library and better C++ integration support.
> make buffer 'const void*' in output functions, as in write(2), fwrite(3) etc.

- nbd-server.c
When the nbd-client disconnects from a TLS connection, the gnutls_record_recv function will return a zero value. Due to a faulty/missing check, this causes the readit_tls call to enter an infinite loop, with all terrible consequences that this has. This is a very problematic bug that causes a full CPU usage, and is only treatable by killing the nbd-server.
This fix adds the missing check and an appropriate message that terminates the forked server child graceously.
> Fix nbd-server infinite loop for TLS

- cliserv.c
- cliserv.h
- nbd-client.c
When nbd-client tries to connect to nbd device, it talks to kernel via netlink. If the nbd device is taken and locked by other process like `systemd-udevd`, kernel will return EBUSY to nbd client. However, nbd client just hide this error code with error message to check `dmesg` logs.
Checking the `dmesg` logs is error-prone and not friendly for other caller program. Instead, nbd-client should return the error code to the caller to handle it properly.
> nbd-client: Exit with error code other than EXIT_FAILURE
